name: HCL OneTest Performance

on:
    workflow_dispatch:
        inputs:
            imshared:
                description: 'IMShared Location'
                required: false
            workspace:
                description: 'Workspace'
                required: true
            project:
                description: 'Project'
                required: true
            suite:
                description: 'Test Suite Name'
                required: true
            multipleValues:
                description: 'Multiple Values'
                required: false

jobs:

    WebUI-Action:
        runs-on: self-hosted
        name: HCL OneTest Performance
        steps:
         - name: HCL OneTest Performances
           uses: SonaHJ/RPTAction@main
           with:
            imshared: '${{ github.event.inputs.imshared }}'
            workspace: '${{ github.event.inputs.workspace }}'
            project: '${{ github.event.inputs.project }}'
            suite: '${{ github.event.inputs.suite }}'
            multipleValues: '${{ github.event.inputs.multipleValues }}'
